### ISSUE TITLE
Assertion error

### ISSUE THREAD

**Issue by qarth** [MatthewVD/ultpit#2]
Hey,

I managed to build the main app (except pseudoflow, I don't know how to compile using make and gcc) on windows using `rdmd -m64 -O --build-only app.d` however I get the following error when running the program.

`[2017-Mar-10 14:59:16.7764917] Begin optimizing`
`core.exception.AssertError@.\src\ultpit\engine.d(34): Assertion failure`

In engine.d  on line 34 it says `assert(solution.length == data.length);` so I commented it out to fix it and result.txt is the same as expected.txt.

Also I wonder if it would be any faster implemented in Golang due to it's ease of concurrency? A cool idea I had was what if the ui was a web app. I don't think I could port it myself but extending the cli app to a web app would be fairly easy in Go, I don't know about D. 

Also, I thought that visualising the result could be done by outputting the results as a Voxelman map (https://github.com/MrSmith33/voxelman) or the result could be output as a Minecraft map and visualised using this: https://overviewer.org/example/#/-310/64/90/-4/0/0 but Minecraft can only render cube shaped blocks. Just a thought.

I wrote a csv parser in Go which reads a block model in datamine format and calculates the block economic value for input into ultpit, it's almost finished if you're interested.

Thanks,

Rob

**Comment by MatthewVD** [comment]
Hey Qarth,

That is a very interesting assertion to fail. Were you using one of the included datasets or do you have a different dataset that you could provide so I can reproduce the issue?

Concurrency does not have a meaningful impact on the main 'slow' area of the application. The Lerchs Grossmann algorithm is not parallel, and it is not immediately obvious how to make it so. If you wanted to use multiple instances of lg3d to solve multiple problems (say multiple realizations in parallel, or to do parametric analysis) then you could add some higher level parallelism. However, it would be far more efficient to actually implement pseudoflow.

You are welcome to port the code, or manipulate it how you want. This repository will remain dlang for now, I am not inclined to rewrite everything in golang. You are welcome to write an output method in any format.

Cheers,

**Comment by qarth** [comment]
Hey Mathew,

The error occurred when testing the mclaughlin dataset as shown below:
`root@DESKTOP-UB21P28 MINGW64 /c/D/ultpit/test/mclaughlin_2140342
$ ../../ultpit.exe params.json --input data.txt.gz --output 1403.txt.gz --log 1403.txt

core.exception.AssertError@.\src\ultpit\engine.d(34): Assertion failure
----------------
0x00007FF77F3BE979
0x00007FF77F3AE78C
0x00007FF77F3AE554
0x00007FF77F3ABE7E
0x00007FF77F3AFA89
0x00007FF77F3AEA3B
0x00007FF77F3B55D6
0x00007FF77F381054
0x00007FF77F3C7132
0x00007FF77F3C703F
0x00007FF77F3C70CC
0x00007FF77F3C703F
0x00007FF77F3C6F79
0x00007FF77F381394
0x00007FF77F41F8A1
0x00007FFCF8138364 in BaseThreadInitThunk
0x00007FFCF8A170D1 in RtlUserThreadStart
`
I understand, perhaps I'll grapple with learning D instead.
No opportunities for parallelism, that's a shame. Parametric analysis or use of revenue factors in order to generate many pit shells in parallel would be excellent. I realise my ideas are a bit eccentric but how would you compare the results with that from another package e.g. Whittle's LG algorithm, Vulcan 9.1's push-relabel or Deswik's implimentation of pseudoflow?

Thanks,

Rob

**Comment by MatthewVD** [comment]
Rob,

I will investigate that error, maybe this weekend..

I believe that my implementation of LG is comparable, and possibly faster than Whittle's LG. Two years ago or so I compared a slightly earlier implementation than this public repo against whittle and was about twice as fast in the medium sized test cases I ran (30s vs 60s ish). I have not redone a comparison against Whittle in a long time (I don't have a whittle license!). I can, of course, compare against Vulcan, and I have compared against Hochbaum's Pseudoflow (I assume Deswik's is similar). The results of the time comparison are in the attached paper.

[DeutschGonzalezWilliams.pdf](https://github.com/MatthewVD/ultpit/files/846580/DeutschGonzalezWilliams.pdf)


Lerchs Grossmann is algorithmically slower than Pseudoflow or Push Relabel. Think bubble-sort vs quick-sort. So it's sort of like putting lipstick on a pig at this point ;). I still have some work to do on my implementation of Pseudoflow, but maybe someday I will make it open source as well.

If I may make a suggestion, you could use 'ultpit' as just an external executable and call it from any language you want. 

Cheers,

**Comment by qarth** [comment]
That's a very nice paper! Is there a possibility you can share any scripts from it? The geostatistical simulation is especially interesting. Given that it ran for 9 hours and the results show how fast pseudoflow is... that's a lot of computations haha. 

It would be cool to setup a script which runs a master node and a bunch of workers using Amazon EC2 Spot instances or workers on Google Cloud Platform with autoscaling. That's what I'd like to do but I have to work out how to visualise the results first. It's probably best to just append the result column to a datamine style csv and import it into Deswik (I don't have a Vulcan licence, but v10 looks great!)

Also, when I try to get ultpit running on ubuntu I get a permissions denied error when the pseudoflow library is called. I've tried to chmod +x and chmod 777 the binaries to no avail. Do you have any ideas?

**Comment by qarth** [comment]
I fixed the permissions denied error, it was just the wrong dimacs path.

**Comment by MatthewVD** [comment]
Not sure why the assertion was not working -- I just removed that contract.

It would be fun to set this up to run on the cloud or something like that - Good luck with that ;). 

I don't have the scripts available from that paper, they were mostly one off things calling sgsim a couple hundred times, and then an earlier version of ultpit a couple hundred times as well. Nothing too exciting. 

You could also use paraview for visualization, the vtk format is not too weird. I believe you'll want the STRUCTURED_POINTS data type. Maybe I should add a VTK output format.
